spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # set @@GLOBAL.sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
    url: jdbc:mysql://172.30.34.64:3306/complaint
    username: root
    password: TLMTEAMYLL4523..
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
server:
  port: 8001